'use client';

import React, { useState } from 'react';
import { HelpCircle, ChevronDown, Sparkles, ShieldCheck } from 'lucide-react';

interface FaqItem {
  question: string;
  answer: string;
  badge?: string;
}

const faqData: FaqItem[] = [
  {
    question: 'What is SellDesk?',
    answer:
      'SellDesk is a specialized multi-tenant SaaS commerce platform engineered for Pakistani clothing and fashion brands to streamline WhatsApp customer orders, variant inventory allocation, and multi-channel operations.',
  },
  {
    question: 'Who is SellDesk designed for?',
    answer:
      'SellDesk is built for D2C apparel stores, boutique fashion brands, and multi-location clothing retailers in Pakistan handling high-volume customer inquiries and sales transactions over WhatsApp.',
  },
  {
    question: 'How does WhatsApp fit into SellDesk?',
    answer:
      'SellDesk connects with the WhatsApp Cloud API, allowing customer chats to stream directly into an operational workspace where orders can be extracted, variant stock can be checked, and customer profiles can be built.',
  },
  {
    question: 'How does the AI Engine handle customer messages?',
    answer:
      'The AI Engine parses unstructured WhatsApp messages to recognize customer intent, size choices (S, M, L, XL), color variants, and delivery addresses, generating structured draft order details in seconds.',
  },
  {
    question: 'Does the AI automatically place orders without supervision?',
    answer:
      'No. SellDesk enforces strict human-in-the-loop guardrails. Orders generated by AI remain in a draft state until verified and approved by your store team before final booking.',
    badge: 'Guardrail Enforcement',
  },
  {
    question: 'Can a seller review, edit, or reject AI-generated draft orders?',
    answer:
      'Yes. Store staff can review parsed line items, update sizes or quantities, modify shipping details, or reject invalid draft orders in 1-click from the dashboard.',
  },
  {
    question: 'How does inventory allocation work across variants?',
    answer:
      'Stock levels are synchronized in real time per variant (Size/Color SKU). Once an order is confirmed, stock levels decrement immediately to prevent overselling.',
  },
  {
    question: 'Does SellDesk support Cash on Delivery (COD) tracking?',
    answer:
      'Yes. Orders support Cash on Delivery (COD), Bank Transfer, EasyPaisa, and JazzCash payment tracking, complete with PKR revenue ledgers for your accounting team.',
  },
  {
    question: 'Is courier integration available right now?',
    answer:
      'Direct waybill booking and live consignment tracking for Leopard, TCS, and Trax couriers are planned for the upcoming Slice 9 logistics release. Currently, orders are managed via internal order status tracking.',
    badge: 'Slice 9 Roadmap',
  },
  {
    question: 'How does multi-tenant business isolation work?',
    answer:
      'Each client brand store operates inside an isolated tenant environment protected by X-Tenant-ID scoping and role-based access control (RBAC), ensuring complete data privacy.',
  },
];

export function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section
      id="faq"
      style={{
        padding: '6rem 1.5rem',
        backgroundColor: '#090D16',
        position: 'relative',
        borderTop: '0.0625rem solid rgba(255, 255, 255, 0.06)',
      }}
    >
      <div style={{ maxWidth: '64rem', margin: '0 auto' }}>
        {/* Section Header */}
        <div style={{ textAlign: 'center', marginBottom: '3.5rem' }}>
          <div
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0.5rem',
              padding: '0.375rem 0.875rem',
              borderRadius: '2rem',
              background: 'rgba(99, 102, 241, 0.1)',
              border: '0.0625rem solid rgba(99, 102, 241, 0.25)',
              color: '#818CF8',
              fontSize: '0.8rem',
              fontWeight: 700,
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              marginBottom: '1rem',
            }}
          >
            <HelpCircle style={{ width: '0.9rem', height: '0.9rem' }} />
            <span>Factual Product Knowledge</span>
          </div>

          <h2
            style={{
              fontSize: 'clamp(1.85rem, 3.5vw, 2.75rem)',
              fontWeight: 800,
              color: '#FFFFFF',
              letterSpacing: '-0.02em',
              marginBottom: '1rem',
            }}
          >
            Frequently Asked Questions
          </h2>
          <p
            style={{
              fontSize: '1rem',
              color: '#9CA3AF',
              maxWidth: '38rem',
              margin: '0 auto',
              lineHeight: 1.6,
            }}
          >
            Transparent, accurate answers about SellDesk capabilities, AI guardrails, and upcoming logistics releases.
          </p>
        </div>

        {/* FAQ Accordion List */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {faqData.map((item, index) => {
            const isOpen = openIndex === index;
            const questionId = `faq-question-${index}`;
            const answerId = `faq-answer-${index}`;

            return (
              <div
                key={index}
                className="glass-card"
                style={{
                  borderRadius: '0.875rem',
                  overflow: 'hidden',
                  transition: 'border-color 0.2s ease, background 0.2s ease',
                  borderColor: isOpen ? 'rgba(16, 185, 129, 0.4)' : 'rgba(255, 255, 255, 0.08)',
                  background: isOpen ? 'rgba(17, 24, 39, 0.85)' : 'rgba(17, 24, 39, 0.4)',
                }}
              >
                <button
                  id={questionId}
                  aria-expanded={isOpen}
                  aria-controls={answerId}
                  onClick={() => toggleFaq(index)}
                  style={{
                    width: '100%',
                    padding: '1.25rem 1.5rem',
                    background: 'none',
                    border: 'none',
                    color: '#FFFFFF',
                    textAlign: 'left',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: '1rem',
                    fontSize: '1.05rem',
                    fontWeight: 700,
                    outline: 'none',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexWrap: 'wrap' }}>
                    <span>{item.question}</span>
                    {item.badge && (
                      <span
                        className="badge"
                        style={{
                          fontSize: '0.68rem',
                          padding: '0.15rem 0.5rem',
                          background: item.badge.includes('Slice 9')
                            ? 'rgba(245, 158, 11, 0.15)'
                            : 'rgba(16, 185, 129, 0.15)',
                          color: item.badge.includes('Slice 9') ? '#FBBF24' : '#34D399',
                          border: item.badge.includes('Slice 9')
                            ? '0.0625rem solid rgba(245, 158, 11, 0.3)'
                            : '0.0625rem solid rgba(16, 185, 129, 0.3)',
                        }}
                      >
                        {item.badge}
                      </span>
                    )}
                  </div>
                  <ChevronDown
                    style={{
                      width: '1.25rem',
                      height: '1.25rem',
                      color: isOpen ? '#34D399' : '#6B7280',
                      transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)',
                      transition: 'transform 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
                      flexShrink: 0,
                    }}
                  />
                </button>

                {isOpen && (
                  <div
                    id={answerId}
                    role="region"
                    aria-labelledby={questionId}
                    style={{
                      padding: '0 1.5rem 1.25rem 1.5rem',
                      color: '#9CA3AF',
                      fontSize: '0.925rem',
                      lineHeight: 1.65,
                      borderTop: '0.0625rem solid rgba(255, 255, 255, 0.05)',
                      paddingTop: '0.875rem',
                    }}
                  >
                    {item.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
